#+title: Grid Tkinter
#+language: fr
#+author: Bastien ZALUGAS
#+HTML_DOCTYPE: html5
#+options: <:nil ^:{} broken-links:mark creator:nil date:nil email:nil timestamp:nil toc:2 html-style:nil num:nil html5-fancy:t author:nil
#+setupfile: ./temp-theme.setup

* Utiliser la méthode grid pour l'interface du Puissance 4
:PROPERTIES:
:CUSTOM_ID: grid
:END:

** Ressources
:PROPERTIES:
:CUSTOM_ID: ressources
:END:
#+attr_html: :target _blank
[[https://koor.fr/Python/Tutoriel_Tkinter/tkinter_layout_grid.wp]]

** Pourquoi une Grid pour le Puissance 4 ?
:PROPERTIES:
:CUSTOM_ID: pourquoi-grid
:END:
La méthode grid sert à positionner des éléments (=widgets) dans notre écran en fonction d'un positionnement matriciel. Comme nous utilisons une matrice, c'est à dire une liste de listes, pour placer nos jetons sur le plateau, c'est la méthode la plus adaptée. Il faudra associer à chaque cellule créée le clic de la souris et la fonction qui placera le jeton.

** Etape par étape
:PROPERTIES:
:CUSTOM_ID: etapes
:END:
*** Pré-requis
Il faut déjà avoir initialisé ta grille de puissance 4 avant de paramétrer l'affichage car tu auras besoin de la taille de la grille et des éventuelles valeurs des cases.

*** Initialisation
1. Crée un objet Tk() (=window = tkinter.Tk()=).
2. Configure la fenêtre (titre, fond, etc).
3. Crée un dictionnaire vide qui contiendra tous les widgets de la grille (=widgets = {}=).
   
*** Création des widgets
1. A l'aide d'une double boucle imbriquée (pour parcourir la grille de puissance 4), il faut pour chaque case de la grille créer une cellule pour ton affichage (une cellule sera un Label()). Exemple à l'intérieur de la boucle:
   #+begin_src python
     cell = Label(window, text=" ", bg='white')
     cell.grid(row = i, column = j)
     cell.bind('<Button-1>', clic)
     # clic correspond à une fonction qui faudra définir et qui sera lancée uniquement lorsque l'on clique sur une cellule.
     widgets[(i,j)] = cell
     # utiliser le (i,j) comme clé permettra de retrouver le widget correspondant à une case de la grille de puissance 4.
   #+end_src

2. La fonction clic doit récupérer l'information de la colonne sélectionnée et lancer la fonction qui trouve la bonne ligne pour placer le jeton. Exemple de début de la fonction :
    #+begin_src python
      def clic(event):
	  cell = event.widget
	  col = int(cell.grid_info()['column'])
	  ligne = trouver_ligne(col)
	  # Le reste à implémenter
    #+end_src
